[ui]
screen_ui = grumpyscreen
web_ui = mainsail

[update]
release = stable

[fleet]
# JAG Print Farm configuration
fleet_name = Jag Farm
fleet_size = 6
# Include fleet-wide macros on every printer
extra_config = jag-farm-macros.cfg